alpha_blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :articles
    end
  end
end

alpha_blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

alpha_blog/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

alpha_blog/app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

alpha_blog/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 5 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

alpha_blog/app/controllers/api/v1/articles_controller.rb
module Api
  module V1
    class ArticlesController < ApplicationController
      def index
        articles = Article.order('created_at DESC')
        render json: {status: 'SUCCESS', message: 'Loaded articles', data: articles}, status: :ok
      end

      def show
        # byebug
        begin
          article = Article.find(params[:id])
        rescue => exception
          render json: {status: 'SUCCESS', message: 'No article found', data: article}, status: :ok
        end
        if article
          render json: {status: 'SUCCESS', message: 'Loaded article', data: article}, status: :ok
        end

      end
    end
  end
end

alpha_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must me logged in first to perform this action"
      redirect_to login_path
    end
  end
end

alpha_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
    # byebug
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article updated sucessfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to article_path(@article)
    end
  end

end

alpha_blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5) 
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated successfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

alpha_blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
    render 'about'
  end
end

alpha_blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # byebug
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user_path(user)
    else
      flash.now[:alert] = "Wrong Credentials!"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

alpha_blog/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog, #{@user.username} . You have successfully signed in."
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
    # byebug
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

alpha_blog/app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
  
end

alpha_blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

alpha_blog/app/helpers/pages_helper.rb
module PagesHelper
end

alpha_blog/app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

alpha_blog/app/views/categories/_form.html.erb
<div class="col-10">
  <%= render 'shared/errors', obj: @category %>
  <%= form_with(model: @category, local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :name, "Category name", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter category" %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.submit class: "btn btn-outline-success" %>
    </div>
  <% end %>
</div>

alpha_blog/app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<div class="container">
  
  <div class="row justify-content-center text-center">
    <%= render 'form' %>
  </div>
</div>

alpha_blog/app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories List</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= category.articles.count %> articles</p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

alpha_blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new Category</h1>

<div class="container">
  
  <div class="row justify-content-center text-center">
    <%= render 'form' %>
  </div>
</div>

alpha_blog/app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<div class="text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  <% end %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

alpha_blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|%>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

alpha_blog/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!--<a class="navbar-brand" id="logo" href="#">Alpha Blog</a>-->
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%# <a class="nav-link" href="#">Bloggers</a> %>
        <%= link_to "Bloggers", users_path, class: "nav-link"%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
          <%# <a class="dropdown-item" href="#">Action</a> %>
          <%= link_to "Create new Article", new_article_path, class: "dropdown-item" %>
        <% end %>
          <%# <a class="dropdown-item" href="#">Another action</a> %>
          <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? && current_user.admin? %>
          <%# <a class="dropdown-item" href="#">Action</a> %>
          <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %>
        <% end %>
          <%# <a class="dropdown-item" href="#">Another action</a> %>
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>

      <% if logged_in? %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%# <a class="dropdown-item" href="#">Action</a> %>
          <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
          <%# <a class="dropdown-item" href="#">Another action</a> %>
          <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Delete account", user_path(current_user), method: :delete, data: { confirm: "Are you Sure?" }, class: "dropdown-item text-danger" %>
        </div>
      </li>

        <li class="nav-item">
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Login</a> %>
          <%= link_to 'Log out', logout_path, class: "nav-link", method: :delete %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

alpha_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

alpha_blog/app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Articles', articles_path %> | 
<%= link_to 'Home Page', root_path %>

alpha_blog/app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%# <a class="btn btn-success btn-lg" href="#" role="button">Sign Up</a> %>
    <%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

alpha_blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Error</h4>
    <ul class="text-left">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
 
<% end %>